Repository deepin-community/qemu, pull requests merged in 2024-10, with the labels that each got.

#21 fix: disable powerpc64 system data
  debian/changelog
  debian/control
  debian/control-in
  debian/rules
Labels: do-not-merge/hold

#22 Support Hygon CSV3 guest, support live migration for Hygon CSV3 guest
  debian/changelog
  debian/patches/0045-target-i386-csv-Add-CSV3-context.patch
  debian/patches/0046-target-i386-csv-Add-command-to-initialize-CSV3-conte.patch
  debian/patches/0047-target-i386-csv-Add-command-to-load-data-to-CSV3-gue.patch
  debian/patches/0048-target-i386-csv-Add-command-to-load-vmcb-to-CSV3-gue.patch
  debian/patches/0049-target-i386-cpu-Populate-CPUID-0x8000_001F-when-CSV3.patch
  debian/patches/0050-target-i386-csv-Do-not-register-unregister-guest-sec.patch
  debian/patches/0051-target-i386-csv-Load-initial-image-to-private-memory.patch
  debian/patches/0052-vga-Force-full-update-for-CSV3-guest.patch
  debian/patches/0053-vfio-Only-map-shared-region-for-CSV3-virtual-machine.patch
  debian/patches/0054-linux-headers-update-kernel-headers-to-include-CSV3-.patch
  debian/patches/0055-target-i386-csv-Add-support-to-migrate-the-outgoing-.patch
  debian/patches/0056-target-i386-csv-Add-support-to-migrate-the-incoming-.patch
  debian/patches/0057-target-i386-csv-Add-support-to-migrate-the-outgoing-.patch
  debian/patches/0058-target-i386-csv-Add-support-to-migrate-the-incoming-.patch
  debian/patches/series
Labels: needs-ok-to-test

#23 Add hw/vfio/hct device, which support using ccp in VM
  debian/changelog
  debian/patches/hw-vfio-add-device-hct-based-on-vfio.patch
  debian/patches/hw-vfio-hct-fix-ccp_index-error-caused-by-uninitiali.patch
  debian/patches/hw-vfio-hct-qemu-startup-terminate-once-error-happen.patch
  debian/patches/hw-vfio-hct-update-support-ccp-count-to-48.patch
  debian/patches/series
Labels: ok-to-test

#24 Support running Hygon TKM in CSV virtual machine
  debian/changelog
  debian/patches/hw-i386-pc-add-mem2-option-for-qemu.patch
  debian/patches/hw-misc-psp-pin-the-hugepage-memory-specified-by-mem2.patch
  debian/patches/hw-misc-psp-support-tkm-use-mem2-memory.patch
  debian/patches/series
Labels: ok-to-test
